# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-06-04 17:57
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApplication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='incroduction',
            field=models.TextField(default=datetime.datetime(2017, 6, 4, 17, 57, 22, 211126, tzinfo=utc), max_length=2000),
            preserve_default=False,
        ),
    ]
