# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-06-08 14:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApplication', '0006_auto_20170608_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ForeignKey(default='Brak Kategorii', on_delete=django.db.models.deletion.CASCADE, to='BlogApplication.Category'),
        ),
    ]
