# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-06-08 15:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApplication', '0007_auto_20170608_1600'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.ManyToManyField(default='Brak Kategorii', to='BlogApplication.Category'),
        ),
    ]
